/*FUNCION PARA CALCULAR EL PRECIO DE VENTA CON EL PRIMER PARAMETRO COMO EL COSTO Y EL SEGUNDO COMO EL PORCENTAJE DE GANANCIA */
SELECT calcular_precioVenta(44500,30) AS PrecioVenta;
/*FUNCION PARA CALCULAR EL PRECIO DE VENTA FINAL SUMANDO EL IMPUESTO IVA */
SELECT calcular_precioFinal(57850) AS PrecioFinal;

ALTER TABLE `panialera_renacer`.`articulo` 
CHANGE COLUMN `IVA` `IVA` tinyint DEFAULT 21 ;

INSERT INTO articulo (costo,precioVenta,precioFinal,stock)
VALUES
(44500,57850,69998.5,25);

SELECT * FROM articulo;
